// <auto-generated />
using System;
using Maffei.API.DataModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Maffei.API.Migrations
{
    [DbContext(typeof(AdminContext))]
    partial class AdminContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Maffei.API.DataModels.Abone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrencyUnitId")
                        .HasColumnType("int");

                    b.Property<int>("KdvId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OpeningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyUnitId");

                    b.HasIndex("KdvId");

                    b.ToTable("Abone");
                });

            modelBuilder.Entity("Maffei.API.DataModels.CalculationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CalculationType");
                });

            modelBuilder.Entity("Maffei.API.DataModels.CurrencyUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Money")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CurrencyUnit");
                });

            modelBuilder.Entity("Maffei.API.DataModels.IndexCalculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AboneId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CalculationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CalculationTypeId")
                        .HasColumnType("int");

                    b.Property<float>("ConsumptionAmount")
                        .HasColumnType("real");

                    b.Property<float>("FirstIndex")
                        .HasColumnType("real");

                    b.Property<float>("LastIndex")
                        .HasColumnType("real");

                    b.Property<float>("RecipeTotalPrice")
                        .HasColumnType("real");

                    b.Property<float>("TariffKdvPrice")
                        .HasColumnType("real");

                    b.Property<float>("UnitPrice")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("AboneId");

                    b.HasIndex("CalculationTypeId");

                    b.ToTable("IndexCalculation");
                });

            modelBuilder.Entity("Maffei.API.DataModels.Kdv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<float>("KdvRatio")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Kdv");
                });

            modelBuilder.Entity("Maffei.API.DataModels.Abone", b =>
                {
                    b.HasOne("Maffei.API.DataModels.CurrencyUnit", "CurrencyUnit")
                        .WithMany()
                        .HasForeignKey("CurrencyUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maffei.API.DataModels.Kdv", "Kdv")
                        .WithMany()
                        .HasForeignKey("KdvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrencyUnit");

                    b.Navigation("Kdv");
                });

            modelBuilder.Entity("Maffei.API.DataModels.IndexCalculation", b =>
                {
                    b.HasOne("Maffei.API.DataModels.Abone", "Abone")
                        .WithMany()
                        .HasForeignKey("AboneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maffei.API.DataModels.CalculationType", "CalculationType")
                        .WithMany()
                        .HasForeignKey("CalculationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abone");

                    b.Navigation("CalculationType");
                });
#pragma warning restore 612, 618
        }
    }
}
